version: '3.7'

services:
   atlangular:
      container_name: atlangular
      build:
         content: .
         dockerfile: Dockerfile
      volumes:
         - '.:/app'
         - '/app/node_modules'
      ports:
         - '4201:4200'
